name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: readerly
        options: >-
          --health-cmd="pg_isready -U postgres -d readerly"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 6379:6379

    env:
      # Readerly backend env
      NODE_ENV: test
      BACKEND_PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/readerly?schema=public
      REDIS_URL: redis://localhost:6379
      JWT_SECRET: ci-secret-ci-secret-1234567890
      CORS_ALLOW_ORIGIN: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Prisma generate
        working-directory: backend
        run: npx prisma generate

      - name: Apply Prisma migrations
        working-directory: backend
        run: npx prisma migrate deploy

      - name: Create FTS index (optional but recommended)
        working-directory: backend
        run: npm run fts:index

      - name: Run backend tests with coverage
        working-directory: backend
        run: npm run test:coverage

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage